ALTER TABLE rally ADD championship TEXT;
ALTER TABLE rally ADD start INTEGER NOT NULL DEFAULT 0;
ALTER TABLE rally ADD `end` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE rally ADD distance_meters INTEGER NOT NULL DEFAULT 0;
ALTER TABLE rally ADD started INTEGER NOT NULL DEFAULT 0;
ALTER TABLE rally ADD finished INTEGER NOT NULL DEFAULT 0;
