addSbtPlugin("io.spray"          % "sbt-revolver" % "0.10.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.9.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("de.gccc.sbt"       % "sbt-jib"      % "1.3.4")
addSbtPlugin("com.github.sbt"    % "sbt-dynver"   % "5.0.1")
