addSbtPlugin("org.scala-js"                % "sbt-scalajs"   % "1.13.1")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta40")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"  % "2.5.0")
addSbtPlugin("de.heikoseeberger"           % "sbt-header"    % "5.9.0")
addSbtPlugin("io.github.davidgregory084"   % "sbt-tpolecat"  % "0.4.2")
addSbtPlugin("io.spray"                    % "sbt-revolver"  % "0.10.0")
addSbtPlugin("de.gccc.sbt"                 % "sbt-jib"       % "1.3.4")
addSbtPlugin("com.github.sbt"              % "sbt-dynver"    % "5.0.1")
