addSbtPlugin("org.scala-js"                % "sbt-scalajs"              % "1.13.1")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"            % "1.0.0-beta40")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"             % "2.4.6")
addSbtPlugin("de.heikoseeberger"           % "sbt-header"               % "5.9.0")
addSbtPlugin("io.github.davidgregory084"   % "sbt-tpolecat"             % "0.4.2")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject" % "1.2.0")
