name: Auto approve PRs by dependabot

on: pull_request_target

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
    - name: Auto approve
      uses: cognitedata/auto-approve-dependabot-action@v3.0.1
      if: github.actor == 'dependabot[bot]' || github.actor == 'scala-steward-2m[bot]'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
