name: deploy

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: actions/configure-pages@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: sbt

    - run: just install
    - run: just build-scala
    - run: just build

    - uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist'
    - uses: actions/deploy-pages@v2
