name: deploy

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/configure-pages@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm install

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - run: sbt --client publicProd

    - run: npm run build

    - uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist'
    - uses: actions/deploy-pages@v1
      id: deployment
